"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import os
from setuptools import setup

release_version = os.environ['RELEASE_VERSION']
build_name = os.environ['BUILD_NAME']

APP = ['Cura/cura.py']

DATA_FILES = [
    'Cura/LICENSE', 
    'resources/example', 
    'resources/images', 
    'resources/locale', 
    'resources/meshes', 
    'resources/printers', 
    'resources/xml', 
    'plugins',
    'CuraEngine/build/CuraEngine'
]

PLIST = {
    u'CFBundleName': build_name.lower(),
    u'CFBundleDisplayName': build_name,
    u'CFBundleShortVersionString': release_version,
    u'CFBundleVersion': release_version,
    u'CFBundleIdentifier': u'com.dagoma.'+ build_name.lower(),
    u'LSMinimumSystemVersion': u'10.9',
    u'LSApplicationCategoryType': u'public.app-category.graphics-design'
}

OPTIONS = {
    'iconfile': 'resources/images/cura.icns',
    'bdist_base': 'scripts/darwin/build',
    'dist_dir': 'scripts/darwin/dist',
    'plist': PLIST
}

setup(
    name=build_name,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
