"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Cura/cura.py']
DATA_FILES = [
    'Cura/LICENSE', 
    'resources/example', 
    'resources/images', 
    'resources/locale', 
    'resources/meshes', 
    'resources/printers', 
    'resources/xml', 
    'plugins',
    'CuraEngine/build/CuraEngine']
OPTIONS = {
    'iconfile': 'resources/images/cura.icns',
    'bdist_base': 'scripts/darwin/build',
    'dist_dir': 'scripts/darwin/dist'
}

setup(
    name='CuraByDagoma',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
