#!/bin/bash

export APPDIR="$(dirname "$(readlink -f "$0")")"
export PATH="$APPDIR/usr/bin/:$PATH"
# libwx_gtk2u_adv-3.0.so.0: cannot open shared object file: No such file or directory /usr/lib/x86_64-linux-gnu
# libopenblas.so.0: cannot open shared object file: No such file or directory /usr/lib
# libblas.so.3: cannot open shared object file: No such file or directory /usr/lib/openblas-base
export LD_LIBRARY_PATH="$APPDIR/usr/lib:$APPDIR/usr/lib/x86_64-linux-gnu:$APPDIR/usr/lib/libblas:$APPDIR/usr/lib/lapack:$LD_LIBRARY_PATH"

"$APPDIR"/usr/bin/curabydago $@
